import type { Phase } from '@/lib/types';

export const T72_PHASES: Phase[] = [
  {
    id: 'idle',
    name: 'Idle',
    start: 0.0,
    end: 0.1,
    description: 'Vehicle parked, systems cold. Static technical display.',
    highlights: ['hull', 'turret'],
    color: '#7be3ff',
  },
  {
    id: 'startup',
    name: 'Start-up',
    start: 0.1,
    end: 0.3,
    description: 'V-84 multi-fuel diesel cranked. Exhaust plume and warm-up.',
    highlights: ['engine'],
    color: '#ffb86b',
  },
  {
    id: 'aim',
    name: 'Aim',
    start: 0.3,
    end: 0.5,
    description: 'Turret traverse and 2A46 gun elevation under stabilizer.',
    highlights: ['turret', 'main-gun', 'fcs', 'optics'],
    color: '#ffd66b',
  },
  {
    id: 'maneuver',
    name: 'Maneuver',
    start: 0.5,
    end: 0.7,
    description: 'Forward drive. Tracks roll, road wheels rotate, dust kicks up.',
    highlights: ['tracks', 'engine'],
    color: '#a4ff8a',
  },
  {
    id: 'engage',
    name: 'Engage',
    start: 0.7,
    end: 0.85,
    description: 'Firing sequence: muzzle flash, recoil, autoloader cycle.',
    highlights: ['main-gun', 'autoloader', 'ammo'],
    color: '#ff6b6b',
  },
  {
    id: 'maintenance',
    name: 'Maintenance',
    start: 0.85,
    end: 1.0,
    description: 'Exploded view. Components separate to reveal layout.',
    highlights: ['era', 'engine', 'autoloader', 'ammo'],
    color: '#c08bff',
  },
];
